# Generated by Django 5.2.7 on 2025-10-09 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheLab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgmember',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheLab.employee'),
        ),
    ]
