# Generated by Django 5.2.7 on 2025-10-09 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheLab', '0002_alter_orgmember_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Job',
            new_name='job',
        ),
    ]
